
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.Notebook notebook4;
	
	private global::Gtk.Fixed fixed5;
	
	private global::Gtk.Table table5;
	
	private global::Gtk.FileChooserButton fixedImage_fileChooser1;
	
	private global::Gtk.Label label36;
	
	private global::Gtk.Label label38;
	
	private global::Gtk.Label label39;
	
	private global::Gtk.Label label50;
	
	private global::Gtk.FileChooserButton movingImage_fileChooser1;
	
	private global::Gtk.FileChooserButton movingImage_fileChooser2;
	
	private global::Gtk.Entry registration_outputPrefix_entry1;
	
	private global::Gtk.Label label40;
	
	private global::Gtk.Label label41;
	
	private global::Gtk.Table table6;
	
	private global::Gtk.FileChooserButton fixedImageMask_fileChooser1;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Fixed fixed6;
	
	private global::Gtk.Entry histogramBins_entry1;
	
	private global::Gtk.ComboBox histogramMatching_comboBox1;
	
	private global::Gtk.Label label42;
	
	private global::Gtk.Label label43;
	
	private global::Gtk.Label label44;
	
	private global::Gtk.Label label45;
	
	private global::Gtk.Label label46;
	
	private global::Gtk.Label label47;
	
	private global::Gtk.Label label48;
	
	private global::Gtk.ComboBox numberOfThreads_comboBox1;
	
	private global::Gtk.ComboBox precisionType_comboBox1;
	
	private global::Gtk.Entry splineDistance_entry1;
	
	private global::Gtk.ComboBox transformType_comboBox1;
	
	private global::Gtk.Button registrationButton1;
	
	private global::Gtk.Label label37;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Notebook notebook2;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.FileChooserButton fixedImage_fileChooser;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.FileChooserButton movingImage_fileChooser;
	
	private global::Gtk.Entry registration_outputPrefix_entry;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.FileChooserButton fixedImageMask_fileChooser;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Entry histogramBins_entry;
	
	private global::Gtk.ComboBox histogramMatching_comboBox;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Label label14;
	
	private global::Gtk.Label label15;
	
	private global::Gtk.Label label16;
	
	private global::Gtk.Label label17;
	
	private global::Gtk.ComboBox numberOfThreads_comboBox;
	
	private global::Gtk.ComboBox precisionType_comboBox;
	
	private global::Gtk.Entry splineDistance_entry;
	
	private global::Gtk.ComboBox transformType_comboBox;
	
	private global::Gtk.Button registrationButton;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label28;
	
	private global::Gtk.Label label29;
	
	private global::Gtk.Label label30;
	
	private global::Gtk.Notebook notebook3;
	
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.Label label18;
	
	private global::Gtk.Table table3;
	
	private global::Gtk.Entry atropos_outputPrefix_entry;
	
	private global::Gtk.FileChooserButton inputImage_fileChooser;
	
	private global::Gtk.Label label19;
	
	private global::Gtk.Label label20;
	
	private global::Gtk.Label label21;
	
	private global::Gtk.Label label22;
	
	private global::Gtk.FileChooserButton maskImage_fileChooser;
	
	private global::Gtk.Entry segmentationClasses_Entry;
	
	private global::Gtk.Label label23;
	
	private global::Gtk.Table table4;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.ComboBox denoiseAnatomicalImages_comboBox;
	
	private global::Gtk.Fixed fixed4;
	
	private global::Gtk.Entry imageFileSuffix_entry;
	
	private global::Gtk.ComboBox keepTempFiles_comboBox;
	
	private global::Gtk.Label label24;
	
	private global::Gtk.Label label25;
	
	private global::Gtk.Label label26;
	
	private global::Gtk.Label label27;
	
	private global::Gtk.Label label31;
	
	private global::Gtk.Label label32;
	
	private global::Gtk.Entry maxAtroposIterations_entry;
	
	private global::Gtk.Entry maxN4AtroposIterations_entry;
	
	private global::Gtk.ComboBox priorSegmentationWeight_comboBox;
	
	private global::Gtk.Label label33;
	
	private global::Gtk.Label label34;
	
	private global::Gtk.Label label35;
	
	private global::Gtk.Label label49;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		this.notebook1.ShowBorder = false;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.notebook4 = new global::Gtk.Notebook ();
		this.notebook4.CanFocus = true;
		this.notebook4.Name = "notebook4";
		this.notebook4.CurrentPage = 0;
		// Container child notebook4.Gtk.Notebook+NotebookChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.table5 = new global::Gtk.Table (((uint)(3)), ((uint)(7)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(10));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.fixedImage_fileChooser1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fixedImage_fileChooser1.WidthRequest = 190;
		this.fixedImage_fileChooser1.HeightRequest = 0;
		this.fixedImage_fileChooser1.Name = "fixedImage_fileChooser1";
		this.table5.Add (this.fixedImage_fileChooser1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table5 [this.fixedImage_fileChooser1]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label36 = new global::Gtk.Label ();
		this.label36.Name = "label36";
		this.label36.Xalign = 0F;
		this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("Brain Extraction Probability Mask  ");
		this.table5.Add (this.label36);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table5 [this.label36]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label38 = new global::Gtk.Label ();
		this.label38.Name = "label38";
		this.label38.Xalign = 0F;
		this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("Brain Extraction Template");
		this.table5.Add (this.label38);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table5 [this.label38]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label39 = new global::Gtk.Label ();
		this.label39.Name = "label39";
		this.label39.Xalign = 0F;
		this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("Anatomical Image");
		this.label39.Justify = ((global::Gtk.Justification)(1));
		this.table5.Add (this.label39);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table5 [this.label39]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label50 = new global::Gtk.Label ();
		this.label50.Name = "label50";
		this.label50.Xalign = 0F;
		this.label50.LabelProp = global::Mono.Unix.Catalog.GetString ("Output Prefix");
		this.label50.Justify = ((global::Gtk.Justification)(1));
		this.table5.Add (this.label50);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5 [this.label50]));
		w5.LeftAttach = ((uint)(3));
		w5.RightAttach = ((uint)(4));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.movingImage_fileChooser1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.movingImage_fileChooser1.Name = "movingImage_fileChooser1";
		this.table5.Add (this.movingImage_fileChooser1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table5 [this.movingImage_fileChooser1]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.movingImage_fileChooser2 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.movingImage_fileChooser2.Name = "movingImage_fileChooser2";
		this.table5.Add (this.movingImage_fileChooser2);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5 [this.movingImage_fileChooser2]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.registration_outputPrefix_entry1 = new global::Gtk.Entry ();
		this.registration_outputPrefix_entry1.CanFocus = true;
		this.registration_outputPrefix_entry1.Name = "registration_outputPrefix_entry1";
		this.registration_outputPrefix_entry1.Text = global::Mono.Unix.Catalog.GetString ("synquick_output_");
		this.registration_outputPrefix_entry1.IsEditable = true;
		this.registration_outputPrefix_entry1.InvisibleChar = '•';
		this.table5.Add (this.registration_outputPrefix_entry1);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5 [this.registration_outputPrefix_entry1]));
		w8.LeftAttach = ((uint)(4));
		w8.RightAttach = ((uint)(5));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed5.Add (this.table5);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.table5]));
		w9.X = 30;
		w9.Y = 55;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label40 = new global::Gtk.Label ();
		this.label40.Name = "label40";
		this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("COMPULSORY ARGUMENTS");
		this.label40.Justify = ((global::Gtk.Justification)(2));
		this.label40.WidthChars = 0;
		this.fixed5.Add (this.label40);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label40]));
		w10.X = 30;
		w10.Y = 30;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label41 = new global::Gtk.Label ();
		this.label41.Name = "label41";
		this.label41.LabelProp = global::Mono.Unix.Catalog.GetString ("OPTIONAL ARGUMENTS");
		this.label41.UseMarkup = true;
		this.fixed5.Add (this.label41);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label41]));
		w11.X = 30;
		w11.Y = 190;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.table6 = new global::Gtk.Table (((uint)(5)), ((uint)(6)), false);
		this.table6.Name = "table6";
		this.table6.RowSpacing = ((uint)(6));
		this.table6.ColumnSpacing = ((uint)(6));
		// Container child table6.Gtk.Table+TableChild
		this.fixedImageMask_fileChooser1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fixedImageMask_fileChooser1.Name = "fixedImageMask_fileChooser1";
		this.table6.Add (this.fixedImageMask_fileChooser1);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table6 [this.fixedImageMask_fileChooser1]));
		w12.LeftAttach = ((uint)(4));
		w12.RightAttach = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox6.Add (this.fixed6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed6]));
		w13.Position = 1;
		this.table6.Add (this.hbox6);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table6 [this.hbox6]));
		w14.TopAttach = ((uint)(3));
		w14.BottomAttach = ((uint)(4));
		w14.LeftAttach = ((uint)(4));
		w14.RightAttach = ((uint)(5));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.histogramBins_entry1 = new global::Gtk.Entry ();
		this.histogramBins_entry1.WidthRequest = 60;
		this.histogramBins_entry1.CanFocus = true;
		this.histogramBins_entry1.Name = "histogramBins_entry1";
		this.histogramBins_entry1.Text = global::Mono.Unix.Catalog.GetString ("32");
		this.histogramBins_entry1.IsEditable = true;
		this.histogramBins_entry1.InvisibleChar = '•';
		this.table6.Add (this.histogramBins_entry1);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table6 [this.histogramBins_entry1]));
		w15.TopAttach = ((uint)(3));
		w15.BottomAttach = ((uint)(4));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.histogramMatching_comboBox1 = global::Gtk.ComboBox.NewText ();
		this.histogramMatching_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("False"));
		this.histogramMatching_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("True"));
		this.histogramMatching_comboBox1.Name = "histogramMatching_comboBox1";
		this.histogramMatching_comboBox1.Active = 0;
		this.table6.Add (this.histogramMatching_comboBox1);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table6 [this.histogramMatching_comboBox1]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label42 = new global::Gtk.Label ();
		this.label42.Name = "label42";
		this.label42.Xalign = 0F;
		this.label42.LabelProp = global::Mono.Unix.Catalog.GetString ("Transform Type");
		this.table6.Add (this.label42);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table6 [this.label42]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label43 = new global::Gtk.Label ();
		this.label43.Name = "label43";
		this.label43.Xalign = 0F;
		this.label43.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Threads");
		this.table6.Add (this.label43);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table6 [this.label43]));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label44 = new global::Gtk.Label ();
		this.label44.Name = "label44";
		this.label44.Xalign = 0F;
		this.label44.LabelProp = global::Mono.Unix.Catalog.GetString ("Histogram Matching");
		this.table6.Add (this.label44);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table6 [this.label44]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label45 = new global::Gtk.Label ();
		this.label45.Name = "label45";
		this.label45.Xalign = 0F;
		this.label45.LabelProp = global::Mono.Unix.Catalog.GetString ("Precision Type");
		this.table6.Add (this.label45);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table6 [this.label45]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label46 = new global::Gtk.Label ();
		this.label46.Name = "label46";
		this.label46.Xalign = 0F;
		this.label46.LabelProp = global::Mono.Unix.Catalog.GetString ("Fixed Image Mask");
		this.table6.Add (this.label46);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table6 [this.label46]));
		w21.LeftAttach = ((uint)(3));
		w21.RightAttach = ((uint)(4));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label47 = new global::Gtk.Label ();
		this.label47.Name = "label47";
		this.label47.Xalign = 0F;
		this.label47.LabelProp = global::Mono.Unix.Catalog.GetString ("Spline Distance");
		this.table6.Add (this.label47);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table6 [this.label47]));
		w22.TopAttach = ((uint)(4));
		w22.BottomAttach = ((uint)(5));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.label48 = new global::Gtk.Label ();
		this.label48.Name = "label48";
		this.label48.Xalign = 0F;
		this.label48.LabelProp = global::Mono.Unix.Catalog.GetString ("Histogram Bins");
		this.table6.Add (this.label48);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table6 [this.label48]));
		w23.TopAttach = ((uint)(3));
		w23.BottomAttach = ((uint)(4));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.numberOfThreads_comboBox1 = global::Gtk.ComboBox.NewText ();
		this.numberOfThreads_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
		this.numberOfThreads_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
		this.numberOfThreads_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
		this.numberOfThreads_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
		this.numberOfThreads_comboBox1.Name = "numberOfThreads_comboBox1";
		this.numberOfThreads_comboBox1.Active = 0;
		this.table6.Add (this.numberOfThreads_comboBox1);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table6 [this.numberOfThreads_comboBox1]));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.precisionType_comboBox1 = global::Gtk.ComboBox.NewText ();
		this.precisionType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("Double"));
		this.precisionType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("Float"));
		this.precisionType_comboBox1.Name = "precisionType_comboBox1";
		this.precisionType_comboBox1.Active = 0;
		this.table6.Add (this.precisionType_comboBox1);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table6 [this.precisionType_comboBox1]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(1));
		w25.RightAttach = ((uint)(2));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.splineDistance_entry1 = new global::Gtk.Entry ();
		this.splineDistance_entry1.WidthRequest = 43;
		this.splineDistance_entry1.CanFocus = true;
		this.splineDistance_entry1.Name = "splineDistance_entry1";
		this.splineDistance_entry1.Text = global::Mono.Unix.Catalog.GetString ("26");
		this.splineDistance_entry1.IsEditable = true;
		this.splineDistance_entry1.InvisibleChar = '•';
		this.table6.Add (this.splineDistance_entry1);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table6 [this.splineDistance_entry1]));
		w26.TopAttach = ((uint)(4));
		w26.BottomAttach = ((uint)(5));
		w26.LeftAttach = ((uint)(1));
		w26.RightAttach = ((uint)(2));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.transformType_comboBox1 = global::Gtk.ComboBox.NewText ();
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("translation"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("rigid"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + affine"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + affine + deformable syn"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + deformable syn"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("deformable syn only"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + affine + deformable b-spline syn"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + deformable b-spline syn"));
		this.transformType_comboBox1.AppendText (global::Mono.Unix.Catalog.GetString ("deformable b-spline syn only"));
		this.transformType_comboBox1.WidthRequest = 296;
		this.transformType_comboBox1.Name = "transformType_comboBox1";
		this.transformType_comboBox1.Active = 6;
		this.table6.Add (this.transformType_comboBox1);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table6 [this.transformType_comboBox1]));
		w27.TopAttach = ((uint)(1));
		w27.BottomAttach = ((uint)(2));
		w27.LeftAttach = ((uint)(4));
		w27.RightAttach = ((uint)(5));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed5.Add (this.table6);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.table6]));
		w28.X = 30;
		w28.Y = 220;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.registrationButton1 = new global::Gtk.Button ();
		this.registrationButton1.WidthRequest = 180;
		this.registrationButton1.HeightRequest = 50;
		this.registrationButton1.CanFocus = true;
		this.registrationButton1.Name = "registrationButton1";
		this.registrationButton1.UseUnderline = true;
		this.registrationButton1.Label = global::Mono.Unix.Catalog.GetString ("Run Registration");
		this.fixed5.Add (this.registrationButton1);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.registrationButton1]));
		w29.X = 520;
		w29.Y = 330;
		this.notebook4.Add (this.fixed5);
		// Notebook tab
		this.label37 = new global::Gtk.Label ();
		this.label37.Name = "label37";
		this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("antsBrainExtraction");
		this.notebook4.SetTabLabel (this.fixed5, this.label37);
		this.label37.ShowAll ();
		// Notebook tab
		global::Gtk.Label w31 = new global::Gtk.Label ();
		w31.Visible = true;
		this.notebook4.Add (w31);
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.notebook4.SetTabLabel (w31, this.label11);
		this.label11.ShowAll ();
		this.notebook1.Add (this.notebook4);
		// Notebook tab
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Brain Extraction");
		this.notebook1.SetTabLabel (this.notebook4, this.label9);
		this.label9.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(7)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(10));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.fixedImage_fileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fixedImage_fileChooser.WidthRequest = 190;
		this.fixedImage_fileChooser.HeightRequest = 0;
		this.fixedImage_fileChooser.Name = "fixedImage_fileChooser";
		this.table1.Add (this.fixedImage_fileChooser);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixedImage_fileChooser]));
		w33.LeftAttach = ((uint)(1));
		w33.RightAttach = ((uint)(2));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Fixed Image");
		this.label4.Justify = ((global::Gtk.Justification)(1));
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Moving Image");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w35.TopAttach = ((uint)(1));
		w35.BottomAttach = ((uint)(2));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Output Prefix");
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w36.TopAttach = ((uint)(2));
		w36.BottomAttach = ((uint)(3));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.movingImage_fileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.movingImage_fileChooser.Name = "movingImage_fileChooser";
		this.table1.Add (this.movingImage_fileChooser);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1 [this.movingImage_fileChooser]));
		w37.TopAttach = ((uint)(1));
		w37.BottomAttach = ((uint)(2));
		w37.LeftAttach = ((uint)(1));
		w37.RightAttach = ((uint)(2));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.registration_outputPrefix_entry = new global::Gtk.Entry ();
		this.registration_outputPrefix_entry.CanFocus = true;
		this.registration_outputPrefix_entry.Name = "registration_outputPrefix_entry";
		this.registration_outputPrefix_entry.Text = global::Mono.Unix.Catalog.GetString ("synquick_output_");
		this.registration_outputPrefix_entry.IsEditable = true;
		this.registration_outputPrefix_entry.InvisibleChar = '•';
		this.table1.Add (this.registration_outputPrefix_entry);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1 [this.registration_outputPrefix_entry]));
		w38.TopAttach = ((uint)(2));
		w38.BottomAttach = ((uint)(3));
		w38.LeftAttach = ((uint)(1));
		w38.RightAttach = ((uint)(2));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed2.Add (this.table1);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.table1]));
		w39.X = 30;
		w39.Y = 55;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("COMPULSORY ARGUMENTS");
		this.label7.Justify = ((global::Gtk.Justification)(2));
		this.label7.WidthChars = 0;
		this.fixed2.Add (this.label7);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label7]));
		w40.X = 30;
		w40.Y = 30;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("OPTIONAL ARGUMENTS");
		this.label8.UseMarkup = true;
		this.fixed2.Add (this.label8);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label8]));
		w41.X = 30;
		w41.Y = 190;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.table2 = new global::Gtk.Table (((uint)(5)), ((uint)(6)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.fixedImageMask_fileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fixedImageMask_fileChooser.Name = "fixedImageMask_fileChooser";
		this.table2.Add (this.fixedImageMask_fileChooser);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixedImageMask_fileChooser]));
		w42.LeftAttach = ((uint)(4));
		w42.RightAttach = ((uint)(5));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox5.Add (this.fixed1);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed1]));
		w43.Position = 1;
		this.table2.Add (this.hbox5);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox5]));
		w44.TopAttach = ((uint)(3));
		w44.BottomAttach = ((uint)(4));
		w44.LeftAttach = ((uint)(4));
		w44.RightAttach = ((uint)(5));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.histogramBins_entry = new global::Gtk.Entry ();
		this.histogramBins_entry.WidthRequest = 60;
		this.histogramBins_entry.CanFocus = true;
		this.histogramBins_entry.Name = "histogramBins_entry";
		this.histogramBins_entry.Text = global::Mono.Unix.Catalog.GetString ("32");
		this.histogramBins_entry.IsEditable = true;
		this.histogramBins_entry.InvisibleChar = '•';
		this.table2.Add (this.histogramBins_entry);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table2 [this.histogramBins_entry]));
		w45.TopAttach = ((uint)(3));
		w45.BottomAttach = ((uint)(4));
		w45.LeftAttach = ((uint)(1));
		w45.RightAttach = ((uint)(2));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.histogramMatching_comboBox = global::Gtk.ComboBox.NewText ();
		this.histogramMatching_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("False"));
		this.histogramMatching_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("True"));
		this.histogramMatching_comboBox.Name = "histogramMatching_comboBox";
		this.histogramMatching_comboBox.Active = 0;
		this.table2.Add (this.histogramMatching_comboBox);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2 [this.histogramMatching_comboBox]));
		w46.TopAttach = ((uint)(2));
		w46.BottomAttach = ((uint)(3));
		w46.LeftAttach = ((uint)(1));
		w46.RightAttach = ((uint)(2));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.Xalign = 0F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Histogram Bins");
		this.table2.Add (this.label10);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
		w47.TopAttach = ((uint)(3));
		w47.BottomAttach = ((uint)(4));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.Xalign = 0F;
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Spline Distance");
		this.table2.Add (this.label12);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
		w48.TopAttach = ((uint)(4));
		w48.BottomAttach = ((uint)(5));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Fixed Image Mask");
		this.table2.Add (this.label13);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table2 [this.label13]));
		w49.LeftAttach = ((uint)(3));
		w49.RightAttach = ((uint)(4));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.Xalign = 0F;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Precision Type");
		this.table2.Add (this.label14);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table2 [this.label14]));
		w50.TopAttach = ((uint)(1));
		w50.BottomAttach = ((uint)(2));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Histogram Matching");
		this.table2.Add (this.label15);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table2 [this.label15]));
		w51.TopAttach = ((uint)(2));
		w51.BottomAttach = ((uint)(3));
		w51.XOptions = ((global::Gtk.AttachOptions)(4));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.Xalign = 0F;
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Threads");
		this.table2.Add (this.label16);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table2 [this.label16]));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.Xalign = 0F;
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Transform Type");
		this.table2.Add (this.label17);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table2 [this.label17]));
		w53.TopAttach = ((uint)(1));
		w53.BottomAttach = ((uint)(2));
		w53.LeftAttach = ((uint)(3));
		w53.RightAttach = ((uint)(4));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.numberOfThreads_comboBox = global::Gtk.ComboBox.NewText ();
		this.numberOfThreads_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
		this.numberOfThreads_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
		this.numberOfThreads_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
		this.numberOfThreads_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
		this.numberOfThreads_comboBox.Name = "numberOfThreads_comboBox";
		this.numberOfThreads_comboBox.Active = 0;
		this.table2.Add (this.numberOfThreads_comboBox);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table2 [this.numberOfThreads_comboBox]));
		w54.LeftAttach = ((uint)(1));
		w54.RightAttach = ((uint)(2));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.precisionType_comboBox = global::Gtk.ComboBox.NewText ();
		this.precisionType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Double"));
		this.precisionType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("Float"));
		this.precisionType_comboBox.Name = "precisionType_comboBox";
		this.precisionType_comboBox.Active = 0;
		this.table2.Add (this.precisionType_comboBox);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table2 [this.precisionType_comboBox]));
		w55.TopAttach = ((uint)(1));
		w55.BottomAttach = ((uint)(2));
		w55.LeftAttach = ((uint)(1));
		w55.RightAttach = ((uint)(2));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.splineDistance_entry = new global::Gtk.Entry ();
		this.splineDistance_entry.WidthRequest = 43;
		this.splineDistance_entry.CanFocus = true;
		this.splineDistance_entry.Name = "splineDistance_entry";
		this.splineDistance_entry.Text = global::Mono.Unix.Catalog.GetString ("26");
		this.splineDistance_entry.IsEditable = true;
		this.splineDistance_entry.InvisibleChar = '•';
		this.table2.Add (this.splineDistance_entry);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table2 [this.splineDistance_entry]));
		w56.TopAttach = ((uint)(4));
		w56.BottomAttach = ((uint)(5));
		w56.LeftAttach = ((uint)(1));
		w56.RightAttach = ((uint)(2));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.transformType_comboBox = global::Gtk.ComboBox.NewText ();
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("translation"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("rigid"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + affine"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + affine + deformable syn"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + deformable syn"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("deformable syn only"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + affine + deformable b-spline syn"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("rigid + deformable b-spline syn"));
		this.transformType_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("deformable b-spline syn only"));
		this.transformType_comboBox.WidthRequest = 296;
		this.transformType_comboBox.Name = "transformType_comboBox";
		this.transformType_comboBox.Active = 6;
		this.table2.Add (this.transformType_comboBox);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table2 [this.transformType_comboBox]));
		w57.TopAttach = ((uint)(1));
		w57.BottomAttach = ((uint)(2));
		w57.LeftAttach = ((uint)(4));
		w57.RightAttach = ((uint)(5));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed2.Add (this.table2);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.table2]));
		w58.X = 30;
		w58.Y = 220;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.registrationButton = new global::Gtk.Button ();
		this.registrationButton.WidthRequest = 180;
		this.registrationButton.HeightRequest = 50;
		this.registrationButton.CanFocus = true;
		this.registrationButton.Name = "registrationButton";
		this.registrationButton.UseUnderline = true;
		this.registrationButton.Label = global::Mono.Unix.Catalog.GetString ("Run Registration");
		this.fixed2.Add (this.registrationButton);
		global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.registrationButton]));
		w59.X = 520;
		w59.Y = 330;
		this.notebook2.Add (this.fixed2);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("antsRegistrationSyNQuick");
		this.notebook2.SetTabLabel (this.fixed2, this.label3);
		this.label3.ShowAll ();
		// Notebook tab
		global::Gtk.Label w61 = new global::Gtk.Label ();
		w61.Visible = true;
		this.notebook2.Add (w61);
		this.label28 = new global::Gtk.Label ();
		this.label28.Name = "label28";
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.notebook2.SetTabLabel (w61, this.label28);
		this.label28.ShowAll ();
		// Notebook tab
		global::Gtk.Label w62 = new global::Gtk.Label ();
		w62.Visible = true;
		this.notebook2.Add (w62);
		this.label29 = new global::Gtk.Label ();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
		this.notebook2.SetTabLabel (w62, this.label29);
		this.label29.ShowAll ();
		this.notebook1.Add (this.notebook2);
		global::Gtk.Notebook.NotebookChild w63 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.notebook2]));
		w63.Position = 1;
		// Notebook tab
		this.label30 = new global::Gtk.Label ();
		this.label30.Name = "label30";
		this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Registration");
		this.notebook1.SetTabLabel (this.notebook2, this.label30);
		this.label30.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.notebook3 = new global::Gtk.Notebook ();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 0;
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("COMPULSORY ARGUMENTS");
		this.fixed3.Add (this.label18);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label18]));
		w64.X = 30;
		w64.Y = 30;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(5)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(10));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.atropos_outputPrefix_entry = new global::Gtk.Entry ();
		this.atropos_outputPrefix_entry.CanFocus = true;
		this.atropos_outputPrefix_entry.Name = "atropos_outputPrefix_entry";
		this.atropos_outputPrefix_entry.Text = global::Mono.Unix.Catalog.GetString ("segm_output_");
		this.atropos_outputPrefix_entry.IsEditable = true;
		this.atropos_outputPrefix_entry.InvisibleChar = '•';
		this.table3.Add (this.atropos_outputPrefix_entry);
		global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table3 [this.atropos_outputPrefix_entry]));
		w65.TopAttach = ((uint)(1));
		w65.BottomAttach = ((uint)(2));
		w65.LeftAttach = ((uint)(4));
		w65.RightAttach = ((uint)(5));
		w65.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.inputImage_fileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.inputImage_fileChooser.WidthRequest = 170;
		this.inputImage_fileChooser.Name = "inputImage_fileChooser";
		this.table3.Add (this.inputImage_fileChooser);
		global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table3 [this.inputImage_fileChooser]));
		w66.LeftAttach = ((uint)(1));
		w66.RightAttach = ((uint)(2));
		w66.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Segmentation Classes");
		this.table3.Add (this.label19);
		global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table3 [this.label19]));
		w67.LeftAttach = ((uint)(3));
		w67.RightAttach = ((uint)(4));
		w67.XOptions = ((global::Gtk.AttachOptions)(4));
		w67.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.Xalign = 0F;
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Output Prefix");
		this.table3.Add (this.label20);
		global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table3 [this.label20]));
		w68.TopAttach = ((uint)(1));
		w68.BottomAttach = ((uint)(2));
		w68.LeftAttach = ((uint)(3));
		w68.RightAttach = ((uint)(4));
		w68.XOptions = ((global::Gtk.AttachOptions)(4));
		w68.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.Xalign = 0F;
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Mask Image    ");
		this.table3.Add (this.label21);
		global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table3 [this.label21]));
		w69.TopAttach = ((uint)(1));
		w69.BottomAttach = ((uint)(2));
		w69.XOptions = ((global::Gtk.AttachOptions)(4));
		w69.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label22 = new global::Gtk.Label ();
		this.label22.Name = "label22";
		this.label22.Xalign = 0F;
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Input Image");
		this.table3.Add (this.label22);
		global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table3 [this.label22]));
		w70.XOptions = ((global::Gtk.AttachOptions)(4));
		w70.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.maskImage_fileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.maskImage_fileChooser.WidthRequest = 140;
		this.maskImage_fileChooser.Name = "maskImage_fileChooser";
		this.table3.Add (this.maskImage_fileChooser);
		global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table3 [this.maskImage_fileChooser]));
		w71.TopAttach = ((uint)(1));
		w71.BottomAttach = ((uint)(2));
		w71.LeftAttach = ((uint)(1));
		w71.RightAttach = ((uint)(2));
		w71.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.segmentationClasses_Entry = new global::Gtk.Entry ();
		this.segmentationClasses_Entry.CanFocus = true;
		this.segmentationClasses_Entry.Name = "segmentationClasses_Entry";
		this.segmentationClasses_Entry.Text = global::Mono.Unix.Catalog.GetString ("1");
		this.segmentationClasses_Entry.IsEditable = true;
		this.segmentationClasses_Entry.InvisibleChar = '•';
		this.table3.Add (this.segmentationClasses_Entry);
		global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table3 [this.segmentationClasses_Entry]));
		w72.LeftAttach = ((uint)(4));
		w72.RightAttach = ((uint)(5));
		w72.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed3.Add (this.table3);
		global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.table3]));
		w73.X = 30;
		w73.Y = 55;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label23 = new global::Gtk.Label ();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("OPTIONAL ARGUMENTS");
		this.fixed3.Add (this.label23);
		global::Gtk.Fixed.FixedChild w74 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label23]));
		w74.X = 30;
		w74.Y = 160;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.table4 = new global::Gtk.Table (((uint)(5)), ((uint)(6)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 180;
		this.button1.HeightRequest = 50;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Run Atropos");
		this.table4.Add (this.button1);
		global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table4 [this.button1]));
		w75.TopAttach = ((uint)(4));
		w75.BottomAttach = ((uint)(5));
		w75.LeftAttach = ((uint)(4));
		w75.RightAttach = ((uint)(5));
		w75.XOptions = ((global::Gtk.AttachOptions)(4));
		w75.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.denoiseAnatomicalImages_comboBox = global::Gtk.ComboBox.NewText ();
		this.denoiseAnatomicalImages_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("False"));
		this.denoiseAnatomicalImages_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("True"));
		this.denoiseAnatomicalImages_comboBox.Name = "denoiseAnatomicalImages_comboBox";
		this.denoiseAnatomicalImages_comboBox.Active = 0;
		this.table4.Add (this.denoiseAnatomicalImages_comboBox);
		global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table4 [this.denoiseAnatomicalImages_comboBox]));
		w76.LeftAttach = ((uint)(4));
		w76.RightAttach = ((uint)(5));
		w76.XOptions = ((global::Gtk.AttachOptions)(4));
		w76.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.HeightRequest = 20;
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.table4.Add (this.fixed4);
		global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed4]));
		w77.TopAttach = ((uint)(3));
		w77.BottomAttach = ((uint)(4));
		w77.LeftAttach = ((uint)(4));
		w77.RightAttach = ((uint)(5));
		w77.XOptions = ((global::Gtk.AttachOptions)(4));
		w77.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.imageFileSuffix_entry = new global::Gtk.Entry ();
		this.imageFileSuffix_entry.WidthRequest = 110;
		this.imageFileSuffix_entry.CanFocus = true;
		this.imageFileSuffix_entry.Name = "imageFileSuffix_entry";
		this.imageFileSuffix_entry.IsEditable = true;
		this.imageFileSuffix_entry.InvisibleChar = '•';
		this.table4.Add (this.imageFileSuffix_entry);
		global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table4 [this.imageFileSuffix_entry]));
		w78.TopAttach = ((uint)(2));
		w78.BottomAttach = ((uint)(3));
		w78.LeftAttach = ((uint)(1));
		w78.RightAttach = ((uint)(2));
		w78.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.keepTempFiles_comboBox = global::Gtk.ComboBox.NewText ();
		this.keepTempFiles_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("False"));
		this.keepTempFiles_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("True"));
		this.keepTempFiles_comboBox.Name = "keepTempFiles_comboBox";
		this.keepTempFiles_comboBox.Active = 0;
		this.table4.Add (this.keepTempFiles_comboBox);
		global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table4 [this.keepTempFiles_comboBox]));
		w79.TopAttach = ((uint)(1));
		w79.BottomAttach = ((uint)(2));
		w79.LeftAttach = ((uint)(4));
		w79.RightAttach = ((uint)(5));
		w79.XOptions = ((global::Gtk.AttachOptions)(4));
		w79.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label24 = new global::Gtk.Label ();
		this.label24.Name = "label24";
		this.label24.Xalign = 0F;
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Denoise Anatomical Images");
		this.table4.Add (this.label24);
		global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table4 [this.label24]));
		w80.LeftAttach = ((uint)(3));
		w80.RightAttach = ((uint)(4));
		w80.XOptions = ((global::Gtk.AttachOptions)(4));
		w80.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label ();
		this.label25.Name = "label25";
		this.label25.Xalign = 0F;
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Image Files Suffix");
		this.table4.Add (this.label25);
		global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table4 [this.label25]));
		w81.TopAttach = ((uint)(2));
		w81.BottomAttach = ((uint)(3));
		w81.XOptions = ((global::Gtk.AttachOptions)(4));
		w81.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label26 = new global::Gtk.Label ();
		this.label26.Name = "label26";
		this.label26.Xalign = 0F;
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Keep Temporary Files");
		this.table4.Add (this.label26);
		global::Gtk.Table.TableChild w82 = ((global::Gtk.Table.TableChild)(this.table4 [this.label26]));
		w82.TopAttach = ((uint)(1));
		w82.BottomAttach = ((uint)(2));
		w82.LeftAttach = ((uint)(3));
		w82.RightAttach = ((uint)(4));
		w82.XOptions = ((global::Gtk.AttachOptions)(4));
		w82.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label27 = new global::Gtk.Label ();
		this.label27.Name = "label27";
		this.label27.Xalign = 0F;
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("Prior Segmentation Weight");
		this.table4.Add (this.label27);
		global::Gtk.Table.TableChild w83 = ((global::Gtk.Table.TableChild)(this.table4 [this.label27]));
		w83.TopAttach = ((uint)(2));
		w83.BottomAttach = ((uint)(3));
		w83.LeftAttach = ((uint)(3));
		w83.RightAttach = ((uint)(4));
		w83.XOptions = ((global::Gtk.AttachOptions)(4));
		w83.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label31 = new global::Gtk.Label ();
		this.label31.Name = "label31";
		this.label31.Xalign = 0F;
		this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Max. Atropos Iterations");
		this.table4.Add (this.label31);
		global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table4 [this.label31]));
		w84.TopAttach = ((uint)(1));
		w84.BottomAttach = ((uint)(2));
		w84.XOptions = ((global::Gtk.AttachOptions)(4));
		w84.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label32 = new global::Gtk.Label ();
		this.label32.Name = "label32";
		this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Max. N4~Atropos Iterations");
		this.table4.Add (this.label32);
		global::Gtk.Table.TableChild w85 = ((global::Gtk.Table.TableChild)(this.table4 [this.label32]));
		w85.XOptions = ((global::Gtk.AttachOptions)(4));
		w85.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.maxAtroposIterations_entry = new global::Gtk.Entry ();
		this.maxAtroposIterations_entry.WidthRequest = 80;
		this.maxAtroposIterations_entry.CanFocus = true;
		this.maxAtroposIterations_entry.Name = "maxAtroposIterations_entry";
		this.maxAtroposIterations_entry.IsEditable = true;
		this.maxAtroposIterations_entry.InvisibleChar = '•';
		this.table4.Add (this.maxAtroposIterations_entry);
		global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table4 [this.maxAtroposIterations_entry]));
		w86.TopAttach = ((uint)(1));
		w86.BottomAttach = ((uint)(2));
		w86.LeftAttach = ((uint)(1));
		w86.RightAttach = ((uint)(2));
		w86.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.maxN4AtroposIterations_entry = new global::Gtk.Entry ();
		this.maxN4AtroposIterations_entry.WidthRequest = 80;
		this.maxN4AtroposIterations_entry.CanFocus = true;
		this.maxN4AtroposIterations_entry.Name = "maxN4AtroposIterations_entry";
		this.maxN4AtroposIterations_entry.IsEditable = true;
		this.maxN4AtroposIterations_entry.InvisibleChar = '•';
		this.table4.Add (this.maxN4AtroposIterations_entry);
		global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table4 [this.maxN4AtroposIterations_entry]));
		w87.LeftAttach = ((uint)(1));
		w87.RightAttach = ((uint)(2));
		w87.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.priorSegmentationWeight_comboBox = global::Gtk.ComboBox.NewText ();
		this.priorSegmentationWeight_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("False"));
		this.priorSegmentationWeight_comboBox.AppendText (global::Mono.Unix.Catalog.GetString ("True"));
		this.priorSegmentationWeight_comboBox.Name = "priorSegmentationWeight_comboBox";
		this.priorSegmentationWeight_comboBox.Active = 0;
		this.table4.Add (this.priorSegmentationWeight_comboBox);
		global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table4 [this.priorSegmentationWeight_comboBox]));
		w88.TopAttach = ((uint)(2));
		w88.BottomAttach = ((uint)(3));
		w88.LeftAttach = ((uint)(4));
		w88.RightAttach = ((uint)(5));
		w88.XOptions = ((global::Gtk.AttachOptions)(4));
		w88.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed3.Add (this.table4);
		global::Gtk.Fixed.FixedChild w89 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.table4]));
		w89.X = 30;
		w89.Y = 190;
		this.notebook3.Add (this.fixed3);
		// Notebook tab
		this.label33 = new global::Gtk.Label ();
		this.label33.Name = "label33";
		this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("antsAtroposN4");
		this.notebook3.SetTabLabel (this.fixed3, this.label33);
		this.label33.ShowAll ();
		// Notebook tab
		global::Gtk.Label w91 = new global::Gtk.Label ();
		w91.Visible = true;
		this.notebook3.Add (w91);
		this.label34 = new global::Gtk.Label ();
		this.label34.Name = "label34";
		this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.notebook3.SetTabLabel (w91, this.label34);
		this.label34.ShowAll ();
		// Notebook tab
		global::Gtk.Label w92 = new global::Gtk.Label ();
		w92.Visible = true;
		this.notebook3.Add (w92);
		this.label35 = new global::Gtk.Label ();
		this.label35.Name = "label35";
		this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
		this.notebook3.SetTabLabel (w92, this.label35);
		this.label35.ShowAll ();
		this.notebook1.Add (this.notebook3);
		global::Gtk.Notebook.NotebookChild w93 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.notebook3]));
		w93.Position = 2;
		// Notebook tab
		this.label49 = new global::Gtk.Label ();
		this.label49.Name = "label49";
		this.label49.LabelProp = global::Mono.Unix.Catalog.GetString ("Segmentation");
		this.notebook1.SetTabLabel (this.notebook3, this.label49);
		this.label49.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 812;
		this.DefaultHeight = 472;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.registrationButton1.Released += new global::System.EventHandler (this.OnRegistrationButtonReleased);
		this.registrationButton.Released += new global::System.EventHandler (this.OnRegistrationButtonReleased);
		this.button1.Pressed += new global::System.EventHandler (this.OnAntroposButtonReleased);
	}
}
